kind: pipeline
name: default

workspace:
  base: /go
  path: src/github.com/costinm/istio-consul

steps:
  - name: build
    image: golang
    commands:
      - go build cmd/istio-consul/istio-consul.go
      - go test pkg/...
